### ISSUE TITLE
Unable to locate publishable resources. Publishing complete.

### ISSUE THREAD

**Issue by bcs-gbl** [ensi-platform/laravel-openapi-server-generator#8]
When I try to publish:
`php artisan vendor:publish --provider="Ensi\LaravelOpenApiServerGenerator\LaravelOpenApiServerGeneratorServiceProvider"`

I get the following message:
```
Unable to locate publishable resources.
Publishing complete.
```

In my composer.json:
`"ensi/laravel-openapi-server-generator": "^0.9.0",`

I already done:
- clear cache,
- delete vendor dir
- and reinstall all composer package

**Comment by reececomo** [comment]
I had the same thing, but solved it by running:

```sh
$ php artisan vendor:publish
```

and selecting `Provider: Ensi\LaravelOpenapiServerGenerator\OpenapiServerGeneratorServiceProvider` option from the interactive menu.
